baseURL = "https://ca.shoogle.net/newfoundland-and-labrador/"
languageCode = "en-US"
title = "Newfoundland and Labrador"
theme = "ln-base"

disableKinds = ["RSS", "robotsTXT"]
enableGitInfo = true

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
  repo = "newfoundland-and-labrador"

[taxonomies]
  shop = "shops"

